name: venturo_core
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  app_settings: ^5.2.0
  build_runner: ^2.4.9
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.7.0
  connectivity_plus: ^6.1.2
  cupertino_icons: ^1.0.2
  curved_labeled_navigation_bar: ^2.0.5
  device_info_plus: ^10.0.1
  dio: ^5.8.0+1
  fast_rsa: ^3.6.1
  firebase_analytics: null
  firebase_auth: null
  firebase_core: null
  flutter:
    sdk: flutter
  flutter_conditional_rendering: ^2.1.0
  flutter_easyloading: ^3.0.5
  flutter_inappwebview: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.1.2
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get: ^4.6.6
  google_fonts: ^6.2.0
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.2.2
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  loadmore: ^2.1.0
  panara_dialogs: ^0.1.5
  pinput: ^5.0.1
  pull_to_refresh: ^2.0.0
  sentry_flutter: ^7.18.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/ic_javacode.png
    - assets/images/ic_google.png
    - assets/images/ic_marker.png
    - assets/images/bg_map.png
    - assets/images/bg_loading.png
    - assets/images/bg_promo1.png
